/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=GeneratedWebsiteEnv` (hash: 65ab1c0e0150278f2f162548a46eabbd)
interface __BaseEnv_GeneratedWebsiteEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	PORTFOLIO_CONTACT_SUBMISSIONS_QUEUE: Queue;
	PORTFOLIO_CONTACT_PRE_RATE_LIMITER: RateLimit;
	PORTFOLIO_CONTACT_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	THE_GROUND_LIVE_ENABLED: "false";
	THE_GROUND_ORGANIZATION_ID: "";
	PORTFOLIO_CONTACT_COLLECTION_ENABLED: "false";
	PORTFOLIO_CONTACT_CONSENT_VERSION: "portfolio-demo-contact-v1";
	PORTFOLIO_TURNSTILE_EXPECTED_HOSTNAME: "portfolio.example.com";
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace /* DOQueueHandler */;
	WORKER_SELF_REFERENCE: Fetcher /* portfolio-demo-wellness-village-worker */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_GeneratedWebsiteEnv {}
}
interface GeneratedWebsiteEnv extends __BaseEnv_GeneratedWebsiteEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "THE_GROUND_LIVE_ENABLED" | "THE_GROUND_ORGANIZATION_ID" | "PORTFOLIO_CONTACT_COLLECTION_ENABLED" | "PORTFOLIO_CONTACT_CONSENT_VERSION" | "PORTFOLIO_TURNSTILE_EXPECTED_HOSTNAME">> {}
}
