/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/contact-sheet-consumer/wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv workers/contact-sheet-consumer/worker-configuration.d.ts` (hash: c48d5fc1a649ba813f2062056b79b062)
interface __BaseEnv_GeneratedEnv {
	GOOGLE_SERVICE_ACCOUNT_CREDENTIALS_JSON: string;
	GOOGLE_SHEET_ID: string;
	GOOGLE_SHEET_RANGE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_SERVICE_ACCOUNT_CREDENTIALS_JSON" | "GOOGLE_SHEET_ID" | "GOOGLE_SHEET_RANGE">> {}
}
